### ISSUE TITLE
Clarify relations of the java libraries

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/model-runner-java#5]
Hi @carlosuc3m,
great to see all the progress of the java libraries!
For adoption, I think it would be very helpful to have some overview which libraries exist and how they relate to each other.
I have created a small PR #4 to add this to the README (as far as I have an overview of the libraries), but I have two more questions:
- Is there any dependency on https://github.com/bioimage-io/core-bioimage-io-python left or are the new java libraries fully independent of it?
- What is the role of https://github.com/bioimage-io/tensorflow-2-java-interface-0.2.0?

**Comment by carlosuc3m** [comment]
Point to the readme https://github.com/bioimage-io/model-runner-java/edit/main/README.md
